# Generated by Django 5.0.6 on 2026-06-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('primary_button_text', models.CharField(max_length=100)),
                ('primary_button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('locale', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='كل سطر يمثل نقطة مميزة (Highlight) منفصلة.')),
                ('stats', models.TextField(blank=True, help_text='يمكن تخزين إحصائيات بشكل JSON أو نص منسق.')),
                ('plans', models.TextField(blank=True, help_text='يمكن تخزين الباقات (Plans) بشكل JSON أو نص منسق.')),
                ('extra_sections', models.TextField(blank=True, help_text='نص منسق أو JSON لأقسام إضافية في صفحة الخدمة.')),
                ('cta_title', models.CharField(blank=True, max_length=255)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(blank=True, max_length=100)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cms.service')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='cms.footerinfo')),
            ],
        ),
    ]
